### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by nixfreak** [planety/kview#1]
Sorry not an issue just a question. 

Is kview for "viewing karax compile projects"? So you import the karax project first then create the view? 

Is this instead of using a web browser to view? 

Sorry for my ignorance.

**Comment by ringabout** [comment]
This is a simple project.For example, when you use proc `login` firstly, it will automatically generate an example html.And it may be helpful for writing CSS file. 
```nim
proc login*(name: string): string {.writeExample.}
```
